#!/bin/bash
#SBATCH --job-name=myjob    # Job name
#SBATCH --mail-type=NONE          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=zihanw8@illinois.edu     # Where to send mail	
#SBATCH --ntasks=1                   # Run on a single CPU
#SBATCH --time=04:00:00               # Time limit hrs:min:sec
#SBATCH --output=Nr=4_log_%j.log   # Standard output and error log

module load anaconda/2019-Oct/3

python3 /home/zihanw8/scratch/dynamics_2020_07/Runs_plain.py 4 $1